services:
  # --- Reverse Proxy ---
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    user: "0:0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yaml"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"      
      - "--certificatesresolvers.myresolver.acme.email=info@buf-app.it"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
      - "./dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml:ro"    
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
      - "8080:8080"
    networks:
      - web

  # --- Database ---
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        DEV_UID: "${DEV_UID}"
        DEV_GID: "${DEV_GID}"
    container_name: synapse_db
    restart: always
    environment:    
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: "BugAppPostGres..2026!"
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    networks:
      - backend

  # --- Matrix Home Server ---
  synapse:
    build:
      context: .
      dockerfile: Dockerfile.synapse
      args:
        DEV_UID: "${DEV_UID}"
        DEV_GID: "${DEV_GID}"
    container_name: synapse
    restart: always
    depends_on:
      - db
    volumes:
      - "./synapse_data:/data"
    networks:
      - web
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse.rule=Host(`${MATRIX_DOMAIN}`)"
      - "traefik.http.routers.synapse.entrypoints=websecure"
      - "traefik.http.routers.synapse.tls=true"
      - "traefik.http.routers.synapse.middlewares=cors-matrix@file"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
      #- "traefik.http.routers.synapse.tls.certresolver=myresolver"

  # --- Element Web Client ---
  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: always
    volumes:
      - "./element/element-config.json:/app/config.json"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.element.rule=Host(`${ELEMENT_DOMAIN}`)"
      - "traefik.http.routers.element.entrypoints=websecure"
      - "traefik.http.routers.element.tls=true"
      - "traefik.http.routers.element.middlewares=cors-matrix@file"
      - "traefik.http.services.element.loadbalancer.server.port=80"
      #- "traefik.http.routers.element.tls.certresolver=myresolver"

networks:
  web:
    external: false
  backend:
    internal: true # Isola il DB dall'esterno