# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "mtr.bug-app.it"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    resources:
    - compress: false
      names:
      - client
      - federation
    tls: false
    type: http
    x_forwarded: true
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/data/mtr.bug-app.it.log.config"
media_store_path: /data/media_store
registration_shared_secret: "*WmSrE_2q56tU.WBc-+b+R4a5&gPHi,Rb=TCrQLAvsiFXg8bEq"
report_stats: false
macaroon_secret_key: "yf*hE#NqBB~.3qZ+,uR9WE1Ai#tJW:5^jVt2KyUO2J7;I8&PW3"
form_secret: "1~3dG&HQ7RN^8lVy0ufzVJ,MIpf.w,#MVpI-#U25e~Dh;pNw+Y"
signing_key_path: "/data/mtr.bug-app.it.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml